# Generated by Django 3.0.8 on 2020-08-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('sowing', models.TextField()),
                ('spacing', models.TextField()),
                ('harvest_min', models.IntegerField(default=1)),
                ('harvest_max', models.IntegerField(default=1)),
                ('companions', models.TextField(default='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ZipZone',
            fields=[
                ('zip_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('min_temp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=100)),
                ('color', models.CharField(default='#C0BD7C', max_length=100)),
                ('location_description', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.CharField(default=',,,,,,,,,,,', max_length=23)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='api.Plant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='api.Zone')),
            ],
            options={
                'unique_together': {('plant', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='PlantSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('date_seeded', models.DateField(blank=True, default=None, null=True)),
                ('date_planted', models.DateField(blank=True, null=True)),
                ('date_harvested', models.DateField(blank=True, default=None, null=True)),
                ('harvest_date_min', models.DateField(blank=True, null=True)),
                ('harvest_date_max', models.DateField(blank=True, null=True)),
                ('plant_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.PlantZone')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='api.Slot')),
            ],
        ),
    ]
