# Generated by Django 3.1 on 2020-08-07 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantzone',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='api.plant'),
        ),
        migrations.AddField(
            model_name='plantzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='api.zone'),
        ),
        migrations.AddField(
            model_name='plantslot',
            name='plant_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.plantzone'),
        ),
        migrations.AddField(
            model_name='plantslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='api.slot'),
        ),
        migrations.AlterUniqueTogether(
            name='plantzone',
            unique_together={('plant', 'zone')},
        ),
    ]
